### PR TITLE
Fix #116 : Java 16 support for ReflectionUtils

### LINKED ISSUE #116: CI fails on JRE 16-ea
```
-------------------------------------------------------------------------------
Test set: org.codehaus.plexus.util.ReflectionUtilsTest
-------------------------------------------------------------------------------
Tests run: 4, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.004 s <<< FAILURE! - in org.codehaus.plexus.util.ReflectionUtilsTest
testComplexVariableAccess(org.codehaus.plexus.util.ReflectionUtilsTest)  Time elapsed: 0.003 s  <<< ERROR!
java.lang.reflect.InaccessibleObjectException: Unable to make field private static final int java.lang.Class.ANNOTATION accessible: module java.base does not "opens java.lang" to unnamed module @461c1eab
	at org.codehaus.plexus.util.ReflectionUtilsTest.testComplexVariableAccess(ReflectionUtilsTest.java:49)
```

### PR DESCRIPTION
**Pull request by axel3rd**
Proposal for #116. It is more a workaround, could break backward compatibility.

If updating fields accessibility becomes really forbidden in Java 16 for "Class", the usage of Reflection should be updated according that.
Functionally, the impact would be minor. Generally the usage of Reflection is on "personal / business" classes, not for concrete use case directly on "Class".

### CODE REVIEW

File: src/main/java/org/codehaus/plexus/util/ReflectionUtils.java [hunk 1]
```diff
@@ -218,6 +218,13 @@ private static void gatherVariablesAndValuesIncludingSuperclasses( Object object
 
         Class<?> clazz = object.getClass();
 
+        if (Class.class.getCanonicalName().equals(clazz.getCanonicalName()))
```
Comment (mkarg) [inline src/main/java/org/codehaus/plexus/util/ReflectionUtils.java:221]: Shouldn't we do this only on Java 16?

Comment (axel3rd) [reply src/main/java/org/codehaus/plexus/util/ReflectionUtils.java:221]: Yes good catch (if Java >= 16 ... It is probable it doesn't change in the future).
I will check the way todo that (*System properties* `java.version` or other, `Runtime.version()`, ... ; with a correct backward compatibility, until Java 1.4 ; I have not prior version any-more ^^)

Comment (axel3rd) [reply src/main/java/org/codehaus/plexus/util/ReflectionUtils.java:221]: > until Java 1.4

Until Java 1.7, due to `maven.compiler.source` Maven property for *plexus-utils* v3.4 (inherited from plexus parent)

Comment (axel3rd) [reply src/main/java/org/codehaus/plexus/util/ReflectionUtils.java:221]: Proposal for change (`Runtime.version()` is only from Java 9): 
```
if (Integer.parseInt(System.getProperty("java.specification.version").split("\\.")[0]) >= 16 && Class.class.getCanonicalName().equals(clazz.getCanonicalName()))
```

----

@mkarg : With Java 11, there is (logically) this warning at execution:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.plexus.util.ReflectionUtils (file:/somewhere/git/plexus-utils/target/classes/) to field java.lang.Class.ANNOTATION
WARNING: Please consider reporting this to the maintainers of org.codehaus.plexus.util.ReflectionUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

I hesitate to include Java 11 in condition to avoid this warning 🤔. WDYT ?

Comment (axel3rd) [reply src/main/java/org/codehaus/plexus/util/ReflectionUtils.java]: > I hesitate to include Java 11 in condition to avoid this warning

A warning is a "mini error" ^^ => v11 included in condition

File: src/main/java/org/codehaus/plexus/util/ReflectionUtils.java [hunk 2]
```diff
@@ -218,6 +219,14 @@ private static void gatherVariablesAndValuesIncludingSuperclasses( Object object
 
         Class<?> clazz = object.getClass();
 
+        if ( Integer.parseInt( System.getProperty( "java.specification.version" ).split( "\\." )[0] ) >= 11
```
Comment (michael-o) [inline src/main/java/org/codehaus/plexus/util/ReflectionUtils.java:222]: Don't we have anything better in place here?

Comment (axel3rd) [reply src/main/java/org/codehaus/plexus/util/ReflectionUtils.java:222]: > Don't we have anything better in place here?

```java
Float.parseFloat( System.getProperty( "java.specification.version" ) )
```

But `Runtime.Version` ([doc](https://docs.oracle.com/javase/9/docs/api/java/lang/Runtime.Version.html)) cannot be used, exist since Java 9 (`plexus-utils` always compatible with Java 7). And without adding some third-part tooling as dependencies, I don't see another way 😢.

I will update commit with *Float* instead *Integer*.

Comment (axel3rd) [reply src/main/java/org/codehaus/plexus/util/ReflectionUtils.java]: > I will update commit with Float instead Integer.

Done

Comment (axel3rd) [reply src/main/java/org/codehaus/plexus/util/ReflectionUtils.java]: @michael-o : Or did you want a better implementation around `System.getProperty( "java.specification.version" )` if value is *null/blanck/notParsable* ?

**Comment by axel3rd** [comment]
Is this PR not relevant ? 😢

File: src/main/java/org/codehaus/plexus/util/ReflectionUtils.java [hunk 3]
```diff
@@ -1,5 +1,7 @@
 package org.codehaus.plexus.util;
 
+import java.lang.reflect.AccessibleObject;
```
Comment (olamy) [inline src/main/java/org/codehaus/plexus/util/ReflectionUtils.java:3]: not sure why this import has been moved here?

**Comment by olamy** [comment]
I guess we do not have much choice..
I'm ok to merge it.
@michael-o  ?

**Comment by michael-o** [comment]
> I guess we do not have much choice..
> I'm ok to merge it.
> @michael-o ?

No opinion, go ahead.

**Comment by olamy** [comment]
@axel3rd  yes it is still relevant. Just please fix the import and we're good to go! Thanks

**Comment by axel3rd** [comment]
> @axel3rd yes it is still relevant. Just please fix the import and we're good to go! Thanks

Good catch for the import 😕, done.
